source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll', '=3.9.3'
    gem 'jekyll-email-protect'
    gem 'jekyll-github-metadata'
    gem 'jekyll-commonmark-ghpages', '~> 0.4.0'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'bibtex-ruby'
    gem 'nokogiri'
end
